version: "3"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD
      - MARIADB_USER=${MEDIAWIKI_DATABASE_USER}
      - MARIADB_DATABASE=${MEDIAWIKI_DATABASE_NAME}
    volumes:
      - "mariadb_data:/bitnami/mariadb"

  mediawiki:
    image: docker.io/bitnami/mediawiki:1
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - MEDIAWIKI_DATABASE_HOST
      - MEDIAWIKI_DATABASE_PORT_NUMBER
      - MEDIAWIKI_DATABASE_USER
      - MEDIAWIKI_DATABASE_NAME
      - ALLOW_EMPTY_PASSWORD
      - MEDIAWIKI_USERNAME
      - MEDIAWIKI_PASSWORD
      - MEDIAWIKI_EMAIL
      - MEDIAWIKI_WIKI_NAME
      - MEDIAWIKI_HOST
      - MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER
      - MEDIAWIKI_EXTERNAL_HTTPS_PORT_NUMBER
      - MEDIAWIKI_ENABLE_HTTPS
      - MEDIAWIKI_SMTP_HOST
      - MEDIAWIKI_SMTP_HOST_ID
      - MEDIAWIKI_SMTP_PORT
      - MEDIAWIKI_SMTP_USER
      - MEDIAWIKI_SMTP_PASSWORD
      - BITNAMI_DEBUG
    volumes:
      - "mediawiki_data:/bitnami/mediawiki"
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
